version: '3'

services:
    shortlink:  # Nome do serviço alterado para "shortlink"
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        container_name: shortlink-laravel  # Nome do container explícito
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8005:80'  # Porta fixa 8005 mapeada para 80 no container
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail

# Removi completamente a seção do mysql já que você usará banco externo

networks:
    sail:
        driver: bridge

# Removi o volume sail-mysql que não será mais necessário
